UploadFileMVC/Models/ErrorViewModel.cs
using System;

namespace UploadFileMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UploadFileMVC/Models/FileModel.cs
namespace UploadFileMVC.Models
{
    public class FileModel
    {
        public string FileName { get; set; }
    }
}

UploadFileMVC/Controllers/DownloadFileController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using UploadFileMVC.Models;

namespace UploadFileMVC.Controllers
{
    public class DownloadFileController : Controller
    {
        private IHostingEnvironment Environment;
        public DownloadFileController(IHostingEnvironment _environment)
        {
            Environment = _environment; 
        }
        public IActionResult ShowPageDownloadFile()
        {
            string[] filePaths = Directory.GetFiles(Path.Combine(this.Environment.WebRootPath, "Files/"));
            List<FileModel> files = new List<FileModel>();
            foreach(string filePath in filePaths)
            {
                files.Add(new FileModel() { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
        }
        public FileResult DownloadFile(string fileName)
        {
            string path = Path.Combine(this.Environment.WebRootPath, "Files/",fileName);
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            return File(bytes, "application/octet-stream", fileName);
        }
    }
}

UploadFileMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using UploadFileMVC.Models;

namespace UploadFileMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UploadFileMVC/Controllers/UploadFileController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace UploadFileMVC.Controllers
{
    public class UploadFileController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IHostingEnvironment Environment;
        public UploadFileController(IHostingEnvironment environment)
        {
            _httpClient = new HttpClient();
            Environment = environment;
        }
        public IActionResult ShowPageUploadFile()
        {
            return View();
        }
        public async Task<IActionResult> UploadFile(IFormFile files)
        {
            string fileName;
            var extension = "." + files.FileName.Split('.')[files.FileName.Split('.').Length - 1];
            fileName = DateTime.Now.Ticks + extension;
            string path = Path.Combine(this.Environment.WebRootPath, "Files/", fileName);
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await files.CopyToAsync(stream);
            }     
            return RedirectToAction("ShowPageDownloadFile", "DownloadFile");
            //var value = JsonConvert.SerializeObject(files);
            //var response = await _httpClient.PostAsync("https://localhost:7021/api/UploadFile/UploadFileToDatabase", new StringContent(value, Encoding.UTF8, "application/json"));
            //if (response.IsSuccessStatusCode)
            //{
            //    return RedirectToAction("Index", "Home");
            //}
            //else return BadRequest();
        }
    }
}

UploadFileMVC/Views/DownloadFile/ShowPageDownloadFile.cshtml
@model IEnumerable<UploadFileMVC.Models.FileModel>

@{
    ViewData["Title"] = "ListFile";
}

<h1>ListFile</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                    @Html.ActionLink("Download", "DownloadFile", new { fileName = item.FileName}) |
            </td>
        </tr>
}
    </tbody>
</table>

UploadFileMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UploadFileMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UploadFileMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UploadFileMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DownloadFile" asp-action="ShowPageDownloadFile">Download Files</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UploadFile" asp-action="ShowPageUploadFile">Upload Files</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UploadFileMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

UploadFileMVC/Views/UploadFile/ShowPageUploadFile.cshtml
@{
    ViewData["Title"] = "ShowPageUploadFile";
}
<div class="row">
    <div class="col-md-5">
        <form method="post" enctype="multipart/form-data" asp-controller="UploadFile" asp-action="UploadFile">
            <div class="form-group">
                <div class="col-md-10">
                    <p>Upload file</p>
                    <input class="form-control" name="files" type="file"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" class="btn btn-success" value="Upload"/>
                </div>
            </div>
        </form>
    </div>
</div>